language: python
python:
- 2.6
- 2.7
- pypy
- 3.2
- 3.3
- 3.4
install:
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements-2.6.txt; fi
- pip install -r requirements.txt
script: nosetests
after_success:
- coveralls
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    python: 2.7
    tags: true
    all_branches: true
  user: sprockets
  password:
    secure: VjpiEYdgOh+FXy0Xh7hoz15OQaViHo0JwkQAZh41EC5CGtLz4hUT3sUxxR0hsBLdFALv7j8yf68UyzyvKho1Rc1apAydDyzGduFBk9jsc9U3ZDjQ2rF+ROWjdjB0PN+yx1BJEui4YeK5W2hCzP9iPs/KRPuce8+UESTDyfZB3Kc=
